network:
  version: 2
  ethernets:
    ens3:
      dhcp4: false
      dhcp-identifier: mac
      optional: true
    ens4:
      dhcp4: false
      addresses:
        - 192.168.5.2/24
      routes:
        - to: default
          via: 192.168.5.1
      nameservers:
        addresses:
          - 192.168.3.2
    ens5:
      dhcp4: false
      addresses:
        - 10.1.1.103/24
