network:
  version: 2
  ethernets:
    ens4:
      dhcp4: false
      addresses:
        - 192.168.3.2/24
      routes:
        - to: default
          via: 192.168.3.1
      nameservers:
        addresses:
          - 192.168.3.2
