NETWORK_NAMES += BRIDGE
NETWORK_NAMES += NATS

BRIDGE_NET_NAME = macyste_bridge
BRIDGE_NET_CIDR = 192.168.3.0/24
BRIDGE_NET_DRIVER = macvlan
BRIDGE_NET_EXTERNAL = true
BRIDGE_NET_INTERFACE = ens4

NATS_NET_NAME = macyste_nats
NATS_NET_CIDR = 10.1.1.0/24
NATS_NET_DRIVER = macvlan
NATS_NET_EXTERNAL = true
NATS_NET_INTERFACE = ens5