apiVersion: v1
kind: Pod
metadata:
  name: macyste-nats-relay
spec:
  volumes:
    - name: relay-config
      hostPath:
        path: ${nats_relay_config_file}
        type: File
    - name: jetstream
      hostPath:
        path: ${nats_relay_js_store_dir}
        type: DirectoryOrCreate
  containers:
    - name: nats-relay
      image: docker.io/library/nats:2.9.18
      args:
      - --config
      - /etc/nats-relay.conf
      env:
      - { name: NATS_POD_IP, value: "${nats_pod_host}" }
      volumeMounts:
      - { name: relay-config, mountPath: /etc/nats-relay.conf, readOnly: true }
      - { name: jetstream, mountPath: /var/lib/nats }
