apiVersion: v1
kind: Pod
metadata:
  name: macyste-websocket-to-websocket-${target}
spec:
  containers:
    - name: proxy
      image: ${websocket_to_websocket_image}
      ports:
      - containerPort: 3000
        protocol: TCP
