apiVersion: v1
kind: Pod
metadata:
  name: macyste-websocket-to-websocket-${target}
spec:
  containers:
    - name: proxy
      image: ${websocket_to_websocket_image}
      ports:
      - containerPort: ${external_port}
        hostPort: ${external_port}
        Protocol: TCP
      env:
      - { name: EXTERNAL_PORT, value: "${external_port}" }
