apiVersion: v1
kind: Pod
metadata:
  name: macyste-autopilot-forwarder
spec:
  containers:
    - name: autopilot-forwarder
      image: ${autopilot_forwarder_image}
      env:
      - { name: NMEA_HOST, value: "${nmea_host}" }
      - { name: NMEA_PORT, value: "${nmea_port}" }
      - { name: NMEA_TCP_LISTENER_HOST, value: "${autopilot_nmea_tcp_host}" }
      - { name: NMEA_TCP_LISTENER_PORT, value: "${autopilot_nmea_tcp_port}" }
