websocket_to_websocket_radar_pod_websocket_to_websocket_extra_vars += \
    target \
    external_port

websocket_to_websocket_radar_pod_websocket_to_websocket_extra_var_target = radar
websocket_to_websocket_radar_pod_websocket_to_websocket_extra_var_external_port = 3100