NETWORK_NAMES += SIMINT
NETWORK_NAMES += MANAGEMENT

SIMINT_NET_NAME = macyste_simint
SIMINT_NET_CIDR = 192.168.166.0/24
SIMINT_NET_DRIVER = macvlan
SIMINT_NET_EXTERNAL = true
SIMINT_NET_INTERFACE = ens3

MANAGEMENT_NET_NAME = macyste_management
MANAGEMENT_NET_CIDR = 192.168.249.0/24
MANAGEMENT_NET_DRIVER = bridge
MANAGEMENT_NET_INTERNAL = true